# Form implementation generated from reading ui file 'd:\python\MindX\Python\PTA\HL\spck\gia hào\Final Exam's Products\gui\homescreen.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1094, 789)
        MainWindow.setStyleSheet("background-color:silver")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 201, 731))
        self.widget.setStyleSheet("background-color:grey")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.profileBtn = QtWidgets.QPushButton(parent=self.widget)
        self.profileBtn.setGeometry(QtCore.QRect(10, 60, 179, 28))
        self.profileBtn.setStyleSheet("background-color:magenta;\n"
"border-radius:10px")
        self.profileBtn.setObjectName("profileBtn")
        self.friendLstBtn = QtWidgets.QPushButton(parent=self.widget)
        self.friendLstBtn.setGeometry(QtCore.QRect(10, 100, 179, 28))
        self.friendLstBtn.setStyleSheet("background-color:lime;\n"
"border-radius:10px")
        self.friendLstBtn.setObjectName("friendLstBtn")
        self.settingBtn = QtWidgets.QPushButton(parent=self.widget)
        self.settingBtn.setGeometry(QtCore.QRect(10, 690, 179, 28))
        self.settingBtn.setStyleSheet("background-color:silver;\n"
"border-radius:10px")
        self.settingBtn.setObjectName("settingBtn")
        self.friend_tab = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.friend_tab.setGeometry(QtCore.QRect(200, 0, 821, 731))
        self.friend_tab.setStyleSheet("background-color:white")
        self.friend_tab.setObjectName("friend_tab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(parent=self.tab)
        self.frame.setGeometry(QtCore.QRect(0, 0, 821, 711))
        self.frame.setStyleSheet("background-color:teal")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 791, 591))
        self.scrollArea.setStyleSheet("background-color:cyan\n"
"")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 772, 589))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents)
        self.textBrowser.setGeometry(QtCore.QRect(500, 400, 256, 31))
        self.textBrowser.setStyleSheet("background-color:teal;\n"
"border-radius:10px\n"
"\n"
"\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 440, 256, 31))
        self.textBrowser_2.setStyleSheet("background-color:white;\n"
"border-radius:10px\n"
"\n"
"\n"
"\n"
"")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents)
        self.textBrowser_3.setGeometry(QtCore.QRect(500, 480, 256, 51))
        self.textBrowser_3.setStyleSheet("background-color:teal;\n"
"border-radius:10px\n"
"\n"
"")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents)
        self.textBrowser_4.setGeometry(QtCore.QRect(10, 540, 256, 31))
        self.textBrowser_4.setStyleSheet("background-color:white;\n"
"border-radius:10px\n"
"\n"
"")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.widget_2 = QtWidgets.QWidget(parent=self.frame)
        self.widget_2.setGeometry(QtCore.QRect(10, 610, 791, 80))
        self.widget_2.setStyleSheet("background-color:cyan\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.widget_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 771, 61))
        self.plainTextEdit.setStyleSheet("background-color:white")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.friend_tab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 821, 701))
        self.frame_2.setStyleSheet("background-color:green")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.frame_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 10, 791, 591))
        self.scrollArea_2.setStyleSheet("background-color:lime")
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 772, 589))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.textBrowser_7 = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents_2)
        self.textBrowser_7.setGeometry(QtCore.QRect(500, 540, 256, 31))
        self.textBrowser_7.setStyleSheet("background-color:green;\n"
"border-radius:10px\n"
"\n"
"")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.frame_2)
        self.widget_3.setGeometry(QtCore.QRect(10, 610, 791, 80))
        self.widget_3.setStyleSheet("background-color:lime\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(parent=self.widget_3)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(10, 10, 771, 61))
        self.plainTextEdit_2.setStyleSheet("background-color:white")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.friend_tab.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_3 = QtWidgets.QFrame(parent=self.tab_3)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 821, 701))
        self.frame_3.setStyleSheet("background-color:olive")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.scrollArea_3 = QtWidgets.QScrollArea(parent=self.frame_3)
        self.scrollArea_3.setGeometry(QtCore.QRect(10, 10, 791, 591))
        self.scrollArea_3.setStyleSheet("background-color:yellow")
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 772, 589))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.widget_4 = QtWidgets.QWidget(parent=self.frame_3)
        self.widget_4.setGeometry(QtCore.QRect(10, 610, 791, 80))
        self.widget_4.setStyleSheet("background-color:yellow\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(parent=self.widget_4)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(10, 10, 771, 61))
        self.plainTextEdit_3.setStyleSheet("background-color:white")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.textBrowser_8 = QtWidgets.QTextBrowser(parent=self.tab_3)
        self.textBrowser_8.setGeometry(QtCore.QRect(510, 550, 256, 31))
        self.textBrowser_8.setStyleSheet("background-color:olive;\n"
"border-radius:10px\n"
"\n"
"")
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.friend_tab.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame_4 = QtWidgets.QFrame(parent=self.tab_4)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 821, 701))
        self.frame_4.setStyleSheet("background-color:purple")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.scrollArea_4 = QtWidgets.QScrollArea(parent=self.frame_4)
        self.scrollArea_4.setGeometry(QtCore.QRect(10, 10, 791, 591))
        self.scrollArea_4.setStyleSheet("background-color:magenta")
        self.scrollArea_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 772, 589))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.widget_5 = QtWidgets.QWidget(parent=self.frame_4)
        self.widget_5.setGeometry(QtCore.QRect(10, 610, 791, 80))
        self.widget_5.setStyleSheet("background-color:magenta\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(parent=self.widget_5)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(10, 10, 771, 61))
        self.plainTextEdit_4.setStyleSheet("background-color:white")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.textBrowser_9 = QtWidgets.QTextBrowser(parent=self.tab_4)
        self.textBrowser_9.setGeometry(QtCore.QRect(510, 550, 256, 31))
        self.textBrowser_9.setStyleSheet("background-color:purple;\n"
"border-radius:10px\n"
"\n"
"")
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.friend_tab.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.frame_5 = QtWidgets.QFrame(parent=self.tab_5)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 821, 701))
        self.frame_5.setStyleSheet("background-color:maroon")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.scrollArea_5 = QtWidgets.QScrollArea(parent=self.frame_5)
        self.scrollArea_5.setGeometry(QtCore.QRect(10, 10, 791, 591))
        self.scrollArea_5.setStyleSheet("background-color:red")
        self.scrollArea_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_5.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 772, 589))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.textBrowser_10 = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents_5)
        self.textBrowser_10.setGeometry(QtCore.QRect(500, 540, 256, 31))
        self.textBrowser_10.setStyleSheet("background-color:maroon;\n"
"border-radius:10px\n"
"\n"
"")
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.widget_6 = QtWidgets.QWidget(parent=self.frame_5)
        self.widget_6.setGeometry(QtCore.QRect(10, 610, 791, 80))
        self.widget_6.setStyleSheet("background-color:red")
        self.widget_6.setObjectName("widget_6")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(parent=self.widget_6)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(10, 10, 771, 61))
        self.plainTextEdit_5.setStyleSheet("background-color:white")
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.friend_tab.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.frame_6 = QtWidgets.QFrame(parent=self.tab_6)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 821, 701))
        self.frame_6.setStyleSheet("background-color:navy")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.scrollArea_6 = QtWidgets.QScrollArea(parent=self.frame_6)
        self.scrollArea_6.setGeometry(QtCore.QRect(10, 10, 791, 591))
        self.scrollArea_6.setStyleSheet("background-color:blue")
        self.scrollArea_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_6.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 772, 589))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.textBrowser_11 = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents_6)
        self.textBrowser_11.setGeometry(QtCore.QRect(500, 540, 256, 31))
        self.textBrowser_11.setStyleSheet("background-color:navy;\n"
"border-radius:10px\n"
"\n"
"")
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.widget_7 = QtWidgets.QWidget(parent=self.frame_6)
        self.widget_7.setGeometry(QtCore.QRect(10, 610, 791, 80))
        self.widget_7.setStyleSheet("background-color:blue")
        self.widget_7.setObjectName("widget_7")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(parent=self.widget_7)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(10, 10, 771, 61))
        self.plainTextEdit_6.setStyleSheet("background-color:white")
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.friend_tab.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1094, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.friend_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "FRIEND.com"))
        self.profileBtn.setText(_translate("MainWindow", "Profile"))
        self.friendLstBtn.setText(_translate("MainWindow", "Your Friends"))
        self.settingBtn.setText(_translate("MainWindow", "Settings"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt; color:#ffffff;\">Yo, dude.</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt; color:#000000;\">Sup.</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt; color:#ffffff;\">Wanna come to my house to play together?</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Sure!</span></p></body></html>"))
        self.plainTextEdit.setPlaceholderText(_translate("MainWindow", "Click here to type and chat."))
        self.friend_tab.setTabText(self.friend_tab.indexOf(self.tab), _translate("MainWindow", "Friend-1"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt; color:#ffffff;\">(text here)</span></p></body></html>"))
        self.plainTextEdit_2.setPlaceholderText(_translate("MainWindow", "Click here to type and chat."))
        self.friend_tab.setTabText(self.friend_tab.indexOf(self.tab_2), _translate("MainWindow", "Friend-2"))
        self.plainTextEdit_3.setPlaceholderText(_translate("MainWindow", "Click here to type and chat."))
        self.textBrowser_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt; color:#ffffff;\">(text here)</span></p></body></html>"))
        self.friend_tab.setTabText(self.friend_tab.indexOf(self.tab_3), _translate("MainWindow", "Friend-3"))
        self.plainTextEdit_4.setPlaceholderText(_translate("MainWindow", "Click here to type and chat."))
        self.textBrowser_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt; color:#ffffff;\">(text here)</span></p></body></html>"))
        self.friend_tab.setTabText(self.friend_tab.indexOf(self.tab_4), _translate("MainWindow", "Friend-4"))
        self.textBrowser_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt; color:#ffffff;\">(text here)</span></p></body></html>"))
        self.plainTextEdit_5.setPlaceholderText(_translate("MainWindow", "Click here to type and chat."))
        self.friend_tab.setTabText(self.friend_tab.indexOf(self.tab_5), _translate("MainWindow", "Friend-5"))
        self.textBrowser_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt; color:#ffffff;\">(text here)</span></p></body></html>"))
        self.plainTextEdit_6.setPlaceholderText(_translate("MainWindow", "Click here to type and chat."))
        self.friend_tab.setTabText(self.friend_tab.indexOf(self.tab_6), _translate("MainWindow", "Friend-6"))
