# Form implementation generated from reading ui file 'd:\python\MindX\Python\PTA\HL\spck\gia hào\Final Exam's Products\gui\profile.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(632, 424)
        Dialog.setStyleSheet("background-color:magenta")
        self.graphicsView = QtWidgets.QGraphicsView(parent=Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(20, 20, 171, 171))
        self.graphicsView.setStyleSheet("background-color:white;\n"
"border-radius:25px\n"
"")
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(210, 70, 361, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(parent=Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(30, 260, 581, 71))
        self.textBrowser.setStyleSheet("background-color:silver")
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 220, 571, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:purple")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 360, 571, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:purple")
        self.label_3.setObjectName("label_3")
        self.friendBtn = QtWidgets.QPushButton(parent=Dialog)
        self.friendBtn.setGeometry(QtCore.QRect(460, 360, 151, 31))
        self.friendBtn.setStyleSheet("background-color:lime;\n"
"border-radius:10px")
        self.friendBtn.setObjectName("friendBtn")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 210, 601, 201))
        self.widget.setStyleSheet("background-color:purple;\n"
"border-radius:10px")
        self.widget.setObjectName("widget")
        self.widget.raise_()
        self.graphicsView.raise_()
        self.label.raise_()
        self.textBrowser.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.friendBtn.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Tony GH"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&quot;just a sandwich lol.&quot;</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "About"))
        self.label_3.setText(_translate("Dialog", "Friends"))
        self.friendBtn.setText(_translate("Dialog", "View"))
