# Form implementation generated from reading ui file 'd:\python\MindX\Python\PTA\HL\spck\lam\gui\addTask.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(401, 394)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 70, 361, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.descriptionTextEdit = QtWidgets.QPlainTextEdit(parent=self.gridLayoutWidget)
        self.descriptionTextEdit.setStyleSheet("")
        self.descriptionTextEdit.setObjectName("descriptionTextEdit")
        self.gridLayout.addWidget(self.descriptionTextEdit, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.topicLineEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.topicLineEdit.setStyleSheet("border-radius:10px;\n"
"padding:10px;")
        self.topicLineEdit.setObjectName("topicLineEdit")
        self.gridLayout.addWidget(self.topicLineEdit, 2, 0, 1, 1)
        self.deadlineDateEdit = QtWidgets.QDateTimeEdit(parent=self.gridLayoutWidget)
        self.deadlineDateEdit.setStyleSheet("\n"
"border-radius:10px;\n"
"padding:10px;")
        self.deadlineDateEdit.setObjectName("deadlineDateEdit")
        self.gridLayout.addWidget(self.deadlineDateEdit, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(210, 330, 174, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveBtn = QtWidgets.QPushButton(parent=self.widget)
        self.saveBtn.setStyleSheet("background-color:lime;\n"
"border-radius:10px;\n"
"padding:10px;")
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout.addWidget(self.saveBtn)
        self.cancelBtn = QtWidgets.QPushButton(parent=self.widget)
        self.cancelBtn.setStyleSheet("background-color:rgb(255, 190, 210);\n"
"border-radius:10px;\n"
"padding:10px;")
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "TASK DETAIL"))
        self.label_3.setText(_translate("Dialog", "Date deadline"))
        self.label_4.setText(_translate("Dialog", "Comment:"))
        self.label_2.setText(_translate("Dialog", "Title:"))
        self.saveBtn.setText(_translate("Dialog", "Save"))
        self.cancelBtn.setText(_translate("Dialog", "Cancel"))
